Traceback (most recent call last):
  File "/home/pranavsatheesh/host_galaxies/py_files/sim_subhalo_property_statistics.py", line 131, in <module>
    find_tng_subhalo_statistics(basepath, save_loc, minN_values)    
  File "/home/pranavsatheesh/host_galaxies/py_files/sim_subhalo_property_statistics.py", line 22, in find_tng_subhalo_statistics
    z_list = np.array([il.groupcat.loadHeader(tng_basepath, snap)['Redshift'].item() 
  File "/home/pranavsatheesh/host_galaxies/py_files/sim_subhalo_property_statistics.py", line 22, in <listcomp>
    z_list = np.array([il.groupcat.loadHeader(tng_basepath, snap)['Redshift'].item() 
  File "/blue/lblecha/pranavsatheesh/.conda/envs/hfrl/lib/python3.10/site-packages/illustris_python/groupcat.py", line 117, in loadHeader
    with h5py.File(gcPath(basePath, snapNum), 'r') as f:
  File "/blue/lblecha/pranavsatheesh/.conda/envs/hfrl/lib/python3.10/site-packages/h5py/_hl/files.py", line 561, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, fcpl, swmr=swmr)
  File "/blue/lblecha/pranavsatheesh/.conda/envs/hfrl/lib/python3.10/site-packages/h5py/_hl/files.py", line 235, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 102, in h5py.h5f.open
FileNotFoundError: [Errno 2] Unable to synchronously open file (unable to open file: name = '/orange/lblecha/aklantbhowmick/GAS_BASED_SEED_MODEL_UNIFORM_RUNS/L12p5n512/AREPO/SM5_TNG//groups_033/fof_subhalo_tab_033.0.hdf5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
Traceback (most recent call last):
  File "/home/pranavsatheesh/host_galaxies/py_files/sim_subhalo_property_statistics.py", line 131, in <module>
    find_tng_subhalo_statistics(basepath, save_loc, minN_values)    
  File "/home/pranavsatheesh/host_galaxies/py_files/sim_subhalo_property_statistics.py", line 22, in find_tng_subhalo_statistics
    z_list = np.array([il.groupcat.loadHeader(tng_basepath, snap)['Redshift'].item() 
  File "/home/pranavsatheesh/host_galaxies/py_files/sim_subhalo_property_statistics.py", line 22, in <listcomp>
    z_list = np.array([il.groupcat.loadHeader(tng_basepath, snap)['Redshift'].item() 
  File "/blue/lblecha/pranavsatheesh/.conda/envs/hfrl/lib/python3.10/site-packages/illustris_python/groupcat.py", line 117, in loadHeader
    with h5py.File(gcPath(basePath, snapNum), 'r') as f:
  File "/blue/lblecha/pranavsatheesh/.conda/envs/hfrl/lib/python3.10/site-packages/h5py/_hl/files.py", line 561, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, fcpl, swmr=swmr)
  File "/blue/lblecha/pranavsatheesh/.conda/envs/hfrl/lib/python3.10/site-packages/h5py/_hl/files.py", line 235, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 102, in h5py.h5f.open
FileNotFoundError: [Errno 2] Unable to synchronously open file (unable to open file: name = '/orange/lblecha/aklantbhowmick/GAS_BASED_SEED_MODEL_UNIFORM_RUNS/L12p5n512/AREPO/SM5_LW10_TNG//groups_033/fof_subhalo_tab_033.0.hdf5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
Traceback (most recent call last):
  File "/home/pranavsatheesh/host_galaxies/py_files/sim_subhalo_property_statistics.py", line 131, in <module>
    find_tng_subhalo_statistics(basepath, save_loc, minN_values)    
  File "/home/pranavsatheesh/host_galaxies/py_files/sim_subhalo_property_statistics.py", line 22, in find_tng_subhalo_statistics
    z_list = np.array([il.groupcat.loadHeader(tng_basepath, snap)['Redshift'].item() 
  File "/home/pranavsatheesh/host_galaxies/py_files/sim_subhalo_property_statistics.py", line 22, in <listcomp>
    z_list = np.array([il.groupcat.loadHeader(tng_basepath, snap)['Redshift'].item() 
  File "/blue/lblecha/pranavsatheesh/.conda/envs/hfrl/lib/python3.10/site-packages/illustris_python/groupcat.py", line 117, in loadHeader
    with h5py.File(gcPath(basePath, snapNum), 'r') as f:
  File "/blue/lblecha/pranavsatheesh/.conda/envs/hfrl/lib/python3.10/site-packages/h5py/_hl/files.py", line 561, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, fcpl, swmr=swmr)
  File "/blue/lblecha/pranavsatheesh/.conda/envs/hfrl/lib/python3.10/site-packages/h5py/_hl/files.py", line 235, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 102, in h5py.h5f.open
FileNotFoundError: [Errno 2] Unable to synchronously open file (unable to open file: name = '/orange/lblecha/aklantbhowmick/GAS_BASED_SEED_MODEL_UNIFORM_RUNS/L12p5n512/AREPO/SM5_LW10_LOWSPIN_TNG//groups_033/fof_subhalo_tab_033.0.hdf5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
Traceback (most recent call last):
  File "/home/pranavsatheesh/host_galaxies/py_files/sim_subhalo_property_statistics.py", line 131, in <module>
    find_tng_subhalo_statistics(basepath, save_loc, minN_values)    
  File "/home/pranavsatheesh/host_galaxies/py_files/sim_subhalo_property_statistics.py", line 22, in find_tng_subhalo_statistics
    z_list = np.array([il.groupcat.loadHeader(tng_basepath, snap)['Redshift'].item() 
  File "/home/pranavsatheesh/host_galaxies/py_files/sim_subhalo_property_statistics.py", line 22, in <listcomp>
    z_list = np.array([il.groupcat.loadHeader(tng_basepath, snap)['Redshift'].item() 
  File "/blue/lblecha/pranavsatheesh/.conda/envs/hfrl/lib/python3.10/site-packages/illustris_python/groupcat.py", line 117, in loadHeader
    with h5py.File(gcPath(basePath, snapNum), 'r') as f:
  File "/blue/lblecha/pranavsatheesh/.conda/envs/hfrl/lib/python3.10/site-packages/h5py/_hl/files.py", line 561, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, fcpl, swmr=swmr)
  File "/blue/lblecha/pranavsatheesh/.conda/envs/hfrl/lib/python3.10/site-packages/h5py/_hl/files.py", line 235, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 102, in h5py.h5f.open
FileNotFoundError: [Errno 2] Unable to synchronously open file (unable to open file: name = '/orange/lblecha/aklantbhowmick/GAS_BASED_SEED_MODEL_UNIFORM_RUNS/L12p5n512/AREPO/SM5_LW10_LOWSPIN_RICH_TNG//groups_033/fof_subhalo_tab_033.0.hdf5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
Traceback (most recent call last):
  File "/home/pranavsatheesh/host_galaxies/py_files/sim_subhalo_property_statistics.py", line 131, in <module>
    find_tng_subhalo_statistics(basepath, save_loc, minN_values)    
  File "/home/pranavsatheesh/host_galaxies/py_files/sim_subhalo_property_statistics.py", line 22, in find_tng_subhalo_statistics
    z_list = np.array([il.groupcat.loadHeader(tng_basepath, snap)['Redshift'].item() 
  File "/home/pranavsatheesh/host_galaxies/py_files/sim_subhalo_property_statistics.py", line 22, in <listcomp>
    z_list = np.array([il.groupcat.loadHeader(tng_basepath, snap)['Redshift'].item() 
  File "/blue/lblecha/pranavsatheesh/.conda/envs/hfrl/lib/python3.10/site-packages/illustris_python/groupcat.py", line 117, in loadHeader
    with h5py.File(gcPath(basePath, snapNum), 'r') as f:
  File "/blue/lblecha/pranavsatheesh/.conda/envs/hfrl/lib/python3.10/site-packages/h5py/_hl/files.py", line 561, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, fcpl, swmr=swmr)
  File "/blue/lblecha/pranavsatheesh/.conda/envs/hfrl/lib/python3.10/site-packages/h5py/_hl/files.py", line 235, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 102, in h5py.h5f.open
FileNotFoundError: [Errno 2] Unable to synchronously open file (unable to open file: name = '/orange/lblecha/IllustrisTNG/Runs/TNG50-1/output/groups_100/fof_subhalo_tab_100.0.hdf5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
