/tmp/slurmd/job60148674/slurm_script: line 20: populationfile: command not found
Traceback (most recent call last):
  File "/home/pranavsatheesh/host_galaxies/py_files/create_control_sample.py", line 59, in <module>
    pop = h5py.File(pop_file, 'r')
  File "/blue/lblecha/pranavsatheesh/.conda/envs/hfrl/lib/python3.10/site-packages/h5py/_hl/files.py", line 561, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, fcpl, swmr=swmr)
  File "/blue/lblecha/pranavsatheesh/.conda/envs/hfrl/lib/python3.10/site-packages/h5py/_hl/files.py", line 235, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 102, in h5py.h5f.open
FileNotFoundError: [Errno 2] Unable to synchronously open file (unable to open file: name = '/home/pranavsatheesh/host_galaxies/py_files/create_control_sample.pypopulation_sort_gas-100_dm-100_star-100_bh-001.hdf5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
